### PR TITLE
Category column not nullable

### PR DESCRIPTION
**Pull request by HousewifeHacker**
In order to create a new alembic script, the previous script had to be changed. The models give category 'Unclassified' if the category cannot be determined from the topic and
categories from fedmsg. The alembic script alters the nullable property
of the category column.

### CODE REVIEW

**Comment by ralphbean** [comment]
Hm, just trying to understand: does this means we'll need to "alembic upgrade -1" and then "alembic upgrade +1"?

**Comment by HousewifeHacker** [comment]
I dont think so. Originally, retrieving the fedmsg configs was done outside the upgrading and downgrading in the determine category script, but creating a new version was causing alembic to read the fedmsg configs incorrectly, even though the fedmsg configs worked correctly for the previous upgrade. I believe just one 'alembic upgrade +1' with the edited script will allow alembic to know which version to upgrade to next, which is the version altering the category column to be nullable=False. Altering the column doesn't work in sqlite

**Comment by HousewifeHacker** [comment]
It took me awhile to discover alembic reads the previous upgrade script outside of the upgrade and downgrade functions, I think to determine the flow or progression of the versions

**Comment by ralphbean** [comment]
Oh!  I see.

Yeah, that would make sense.  Alembic would run that code at "import time".

**Pull request merged**
