### PR TITLE
Add an index on username, category and topic

### PR DESCRIPTION
**Pull request by pypingou**
This should speed up quite a bit the querying of datagrepper.

Thanks @mikeb/@mikebonnet for the hint!

Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

### CODE REVIEW

**Comment by pypingou** [comment]
I dropped indexing the username field of the messages table since it's not really of use for us

**Comment by mikebonnet** [comment]
Looks good! My only suggestion is to rename the alembic script to remove `username`, since it's not being indexed.

**Comment by puiterwijk** [comment]
One piece of note is that this change makes it incompatible with MariaDB and maybe other database engines (if we cared about that), since at least MariaDB does not allow an index over an unlimited TEXT field.

**Comment by pypingou** [comment]
@mikebonnet I'll rename :)

@puiterwijk fair point though I think we already were (incompatible):
``msg_id = Column(UnicodeText, nullable=True, unique=True, default=None, index=True)`` :)

**Comment by pypingou** [comment]
File renamed :)

**Comment by mikebonnet** [comment]
+1 Looks good!

**Comment by ralphbean** [comment]
Released in [python-datanommer-models-0.9.0](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-e1ae8fda45).

**Pull request merged**
