### PR TITLE
Add alembic scripts for indices and composite keys.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by ralphbean** [comment]
Here's a playbook to do the eventual upgrade (with `--limit staging` first, then production later).  https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/playbooks/manual/upgrade/datanommer.yml

**Comment by pypingou** [comment]
:+1: for me

**Comment by pypingou** [comment]
For ansible, is there a way to monitor its progress? I see the delegate_to that should fix the potential timeout question, but then we also do not know how far it is.

**Comment by ralphbean** [comment]
> For ansible, is there a way to monitor its progress

Yes, I have an example handy in the rebuild-fedora-packages playbook that I can re-use for this.  Will post it in a moment.

**Comment by ralphbean** [comment]
This should do it:

``` diff
diff --git a/playbooks/manual/upgrade/datanommer.yml b/playbooks/manual/upgrade/datanommer.yml
index 0b1037a..56a8de6 100644
--- a/playbooks/manual/upgrade/datanommer.yml
+++ b/playbooks/manual/upgrade/datanommer.yml
@@ -110,6 +110,8 @@
     command: /usr/bin/alembic upgrade head
     args:
       chdir: /usr/share/datanommer.models/
+    async: 7200
+    poll: 60

   - name: And... start the backend again
     service: name="fedmsg-hub" state=started
diff --git a/playbooks/manual/upgrade/fmn.yml b/playbooks/manual/upgrade/fmn.yml
index e07e9d0..5cc4feb 100644
--- a/playbooks/manual/upgrade/fmn.yml
+++ b/playbooks/manual/upgrade/fmn.yml
@@ -65,10 +65,14 @@
   tasks:
   - name: Stop the notification backend
     service: name="fedmsg-hub" state=stopped
+
   - name: Upgrade the database
     command: /usr/bin/alembic upgrade head
     args:
       chdir: /usr/share/fmn.lib/
+    async: 7200
+    poll: 60
+
   - name: And... start the backend again
     service: name="fedmsg-hub" state=started
```

**Comment by pypingou** [comment]
:fireworks:

**Comment by ralphbean** [comment]
Correction:  we won't actually get the stdout report of how its progressing until its done:  See ansible/ansible#3887.

**Comment by ralphbean** [comment]
Logs from the dev server on how long it takes to run:

```
$ time alembic upgrade head
INFO  [alembic.migration] Context impl PostgresqlImpl.
INFO  [alembic.migration] Will assume transactional DDL.
INFO  [alembic.migration] Running upgrade 143ec484f5ba -> 999b2d10b4e, Add topic index
INFO  [alembic.migration] Finished in 2456.01s
INFO  [alembic.migration] Running upgrade 999b2d10b4e -> 5a167589eb8e, Add category index
INFO  [alembic.migration] Finished in 661.62s
INFO  [alembic.migration] Running upgrade 5a167589eb8e -> 19bb834d6f9, Add users composite pkey
INFO  [alembic.migration] Running 'DELETE FROM user_messages WHERE username is NULL'
INFO  [alembic.migration] Running 'DELETE FROM user_messages WHERE msg is NULL'
INFO  [alembic.migration] Creating composite primary key
INFO  [alembic.migration] Finished in 665.28s
INFO  [alembic.migration] Running upgrade 19bb834d6f9 -> 1b786d5fc66, Add packages composite pkey
INFO  [alembic.migration] Running 'DELETE FROM package_messages WHERE package is NULL'
INFO  [alembic.migration] Running 'DELETE FROM package_messages WHERE msg is NULL'
INFO  [alembic.migration] Creating composite primary key
INFO  [alembic.migration] Finished in 438.06s

real    70m21.880s
user    0m0.470s
sys     0m0.098s
```

**Pull request merged**
