### PR TITLE
Index the message.{msg_id,timestamp}, user.name, and package.name columns.

### PR DESCRIPTION
**Pull request by lmacken**
I'm not sure if SA will automatically add these to the existing db, or if we'll need to do some alembic magic. :speedboat:

### CODE REVIEW

**Comment by ralphbean** [comment]
> If is primary_key, is index. I think than "index=True" is surplus.

Well, it might be an implementation detail of postgres.  Does sqlite automatically create indexes (does it have such a thing?)

I'd be ok with merging it into devel if you don't object @yograterol.

**Comment by yograterol** [comment]
About the change: http://postgresql.1045698.n5.nabble.com/Is-the-primary-key-constraint-also-an-index-tp1905964p1905967.html

But I don't have problem... :+1:

**Comment by ralphbean** [comment]
Bookkeeping: this addresses #39.

**Comment by ralphbean** [comment]
Hey, I'm going to :+1: this change.  We don't need the alembic upgrades -- our databases (staging and production both) have had the index in place for a long time already.  We don't have any databases that would need the alembic upgrade.

**Pull request merged**
