### PR TITLE
Added alembic configuration, created a migration script

### PR DESCRIPTION
**Pull request by HousewifeHacker**
I have a couple questions on this:
1. Is there ever a time we will have multiple usernames and packages on a single message?
   - Can you provide me some examples of how to generate messages from packages that will have examples of this?  I'm currently only testing with fedmsg-logger
2. I can't default the columns using existing data, so the only time they get a default is through the add function.  If we started passing the needed data to _msg, we could default off of that.
3. Do we want to set any defaults in the migration script for existing logs or is it ok to have them nullable?

I still need to add the tests and documentation for this but wanted to discuss it a little first.

### CODE REVIEW

**Comment by pypingou** [comment]
You may want to adjust the **init** function to add this bits: http://git.fedorahosted.org/cgit/fedocal.git/tree/fedocal/fedocallib/model.py#n62

It creates the alembic table in the database storing its information and allowing upgrade from a situation such as:
- design first model
- first design changes tracked in alembic
- /database created here/
- other design changes tracked in alembic
- /try to upgrade the database using alembic here/
  - this will fail as alembic will fail to apply the first set of changes, the change to **init** aims at preventing this situation.

**Comment by pypingou** [comment]
Just as a note, the code I provide isn't from me but from the Alembic documentation: http://alembic.readthedocs.org/en/latest/tutorial.html#building-an-up-to-date-database-from-scratch

**Comment by HousewifeHacker** [comment]
Still working on testing

**Comment by HousewifeHacker** [comment]
Since we have separate tables for every type of message a many to many is kind of weird since you need an association table per message type.  

So to do something like "give me all messages that have anything to do with libgcc" you would have to query all the different association tables.   

If we merged the tables into 1 message table with a content_type column it would make things much nicer.  Do we have them as separate tables for sharding?

**Comment by ralphbean** [comment]
Yes, for sharding.  I'm worried that down the road, a one single table will have thousands and thousands (millions?) of messages in it, and I'm worried about how postgres will perform.  Admittedly, I haven't actually done any research to see what kind of limits postgres can handle for table sizes efficiently.

If you'd like to merge them all into 1 table, I'm all for giving it a try.  :)  Your call, @HousewifeHacker.

**Comment by ralphbean** [comment]
(You're definitely right that it would make querying nicer.  A `content_type` column would make filtering on it a dream.)

**Comment by ralphbean** [comment]
Awesome work!

**Pull request merged**
