### PR TITLE
Alembic from per topic messages models to one message model

### PR DESCRIPTION
**Pull request by HousewifeHacker**

### CODE REVIEW

**Comment by HousewifeHacker** [comment]
Version 24fc1373d76e (the alembic script written previously to add two columns) should be deleted

**Comment by ralphbean** [comment]
Hum.. I'm getting these errors when I try to follow the documentation.  Any ideas?

```
(datanommer)--- datanommer/datanommer.models ‹develop➔› » ~/.virtualenvs/datanommer/bin/alembic current
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume transactional DDL.
WARNI [fedmsg] Crypto disabled ImportError('No module named M2Crypto',)
Current revision for sqlite:///../datanommer.db: None
(datanommer)--- datanommer/datanommer.models ‹develop➔› » ~/.virtualenvs/datanommer/bin/alembic upgrade head
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume transactional DDL.
WARNI [fedmsg] Crypto disabled ImportError('No module named M2Crypto',)
  Only a single head supported so far...
```

**Comment by HousewifeHacker** [comment]
did you delete the add_usernames_and_pa version? It looks like it may be unsure which version to upgrade to

**Comment by HousewifeHacker** [comment]
Yes, according to the alembic documentation, that means there is a branch of versions. The documentation suggests 'editing the files to be in a straight line' by editing the revision identifiers for upgrade and downgrade. I dont see a reason to keep the original script though, so I just deleted it and made the new script modify None (the original multiple models)

**Comment by ralphbean** [comment]
Cool.  :)

**Pull request merged**
