### PR TITLE
Alembic to provide category where Null

### PR DESCRIPTION
**Pull request by HousewifeHacker**
I believe this will work. Just run 'alembic downgrade -1' then 'alembic upgrade +1'

### CODE REVIEW

**Comment by HousewifeHacker** [comment]
my alembic versions had to remove the first two scripts because I set up datanommer on this machine after the second script. The only changes that should be merged in are the final script

**Comment by ralphbean** [comment]
I think I successfully cherry-picked this in this commit 41c263f77f4e2629eb514201de043bd1b47e705a

Does that look right to you?

**Comment by HousewifeHacker** [comment]
Looks right

**Comment by ralphbean** [comment]
Cool.  Closing as merged.  :shipit:

**Pull request closed without merging**
