### PR TITLE
README.rst Fix links for expired fedmsg.com domain

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by abitrolly** [comment]
Of course there are still more to fix - https://github.com/search?q=org%3Afedora-infra+%22fedmsg.com%22&type=Code

**Review by lcarva — APPROVED** [review]

**Comment by lcarva** [comment]
@mikebonnet could you take a look and merge this? (I don't seem to have access)

**Comment by mikebonnet** [comment]
LGTM!

**Review by mikebonnet — APPROVED** [review]

**Comment by mikebonnet** [comment]
@lcarva I don't have merge permission either.

**Comment by lcarva** [comment]
@ralphbean, how do we get access here? (Should we have it?)

**Comment by ralphbean** [comment]
Ah, there is a data team:  https://github.com/orgs/fedora-infra/teams/data-team

@puiterwijk, would you consider adding @mikebonnet and @lcarva to that group?

**Pull request merged**
