### PR TITLE
Determines category for historical data, before category column

### PR DESCRIPTION
**Pull request by HousewifeHacker**
Im worried this might be slow, so let me know if you can think of a better way. It's an alembic script to loop through all the data that was added before the category column was added, then update the category column using the topic.

### CODE REVIEW

**Comment by ralphbean** [comment]
Cool!  I wouldn't worry about it being slow since it will only get run "once".  No need to over-optimize.  :)

**Comment by ralphbean** [comment]
Hey, that `map_value` work is pretty tight.

**Comment by ralphbean** [comment]
May I request that you make one enhancement before I merge this?  Can you replace the hardcoded list of `filters` with a call to `fedmsg.meta.processors`.  Each item in that list should have a `.__name__` that is the value you're looking for.

**Comment by ralphbean** [comment]
Just a note, this is related to Issue #23.

**Comment by HousewifeHacker** [comment]
I had to change how to access the fedmsg config for use with alembic, but my list of fedmsg.meta.processors.**name** only returned announce, logger, and unhandled. Where does the **name** come from? Im a little lost in the fedmsg code

**Comment by ralphbean** [comment]
Ah, shoot.  If you either `pip install fedmsg_meta_fedora_infrastructure` into your virtualenv or `yum install python-fedmsg-meta-fedora-infrastructure` then you should get the rest of the names.  They're broken out into a plugin like that to keep Fedora-isms separate from fedmsg core.

**Comment by HousewifeHacker** [comment]
For production, I think what Ive done will work, but development is going to be tricky (maybe spotty is a better description) because not all the categories come from fedmsg.meta.processors.**name** . Even with the pip install, I am missing some categories.

**Comment by ralphbean** [comment]
Ah, I see..

``` python
>>> import fedmsg.config
>>> config = fedmsg.config.load_config()
>>> import fedmsg.meta
>>> fedmsg.meta.make_processors(**config)
>>> names = [p.__name__ for p in fedmsg.meta.processors]
>>> [name.lower() for name in sorted(names)]
['bodhi', 'fas', 'pkgdb', 'wiki', 'announce', 'compose', 'fedoraplanet', 'fedoratagger', 'git', 'koji', 'logger', 'meetbot', 'unhandled']
```

Things like `"httpd"` are missing.  When I first wrote datanommer we thought that would be a message type but ended up deciding against it for the time being -- that's why it doesn't show up in `fedmsg.meta`.  `"busmon"` is missing too.  It used to emit messages, but does not do so any longer (I simplified it in Oct or Nov).  The one or two months of messages from it can just be reclassified as "unhandled".

---

Anyways, your commits look good to me.  Let's merge!

**Pull request merged**
